server:
  port: 8088
# devtools
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog?
  flyway:
    baseline-on-migrate: true
# log
logging:
  level:
    com.example.blog: debug
  file:
    name: ${PWD}/logs/blog.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


